#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DisplayPort-2 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config focused_border_color "#90d427"
bspc config normal_border_color "#000000"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

flameshot &
sxhkd &
picom &
nitrogen --restore &

PDIR="$HOME/.config/polybar"

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar -q main -c "$PDIR"/config.ini &
polybar -q ext -c "$PDIR"/config.ini &
